export const FETCHING_SHOP_ITEMS_START = 'FEACHING_SHOP_ITEMS_START';
export const FETCHING_SHOP_ITEMS_SUCCESS = 'FEACHING_SHOP_ITEMS_SUCCESS';
export const FETCHING_SHOP_ITEMS_FAILURE = 'FEACHING_SHOP_ITEMS_FAILURE';
export const CONVERT_CURRENCY = 'CONVERT_CURRENCY';
